### PR TITLE
Model Encoding Cleanup

### PR DESCRIPTION
**Pull request by abuneri**
so yeah, I've noticed these things for awhile, but it finally bugged me enough to clean it up :)

### CODE REVIEW

**Comment by abuneri** [comment]
@FiniteReality good2merge 👍

**Comment by FiniteReality** [comment]
I'm personally a fan of keeping the method calls because they can be optimised out fairly easily and they make debugging easier (e.g. we can breakpoint when a certain field is being accessed, and see the stack trace from there)

**Comment by abuneri** [comment]
sure, I can leave those. but some things also just weren't being encoded properly e.g. a key would end up w/ a util::optional instead of the actual contents. but ill switch it back to the getters soon, gonna leave this PR open for now

**Comment by abuneri** [comment]
invalid now

**Pull request closed without merging**
