### PR TITLE
include: wrap code to 80 columns

### PR DESCRIPTION
**Pull request by edosedgar**
These patch covers just include directory, lib and tests will be sent out in next patchs

### CODE REVIEW

**Comment by FiniteReality** [comment]
It would be better if you had a single PR for everything (assuming I'm understanding this correctly), so I can squash and merge instead.

**Comment by edosedgar** [comment]
Sure, I can, but even tests folder requres to change ~10k lines of code, it takes a time and if it is possible I'd have a several PR, OK, at least two:)

**Comment by FiniteReality** [comment]
You don't need to re-indent catch.hpp; don't make too much work for yourself.

**Comment by edosedgar** [comment]
Really? Hm, ok, it changes a lot, thus I'll send out soon patches

**Pull request closed without merging**
