### PR TITLE
[Websocket] Event Listener/Dispatcher and Event Enums

### PR DESCRIPTION
**Pull request by abuneri**
This is a nice event emitter/dispatcher that lets ppl pass in lambdas or void funcs when listening for gateway events.
It also makes it very easy to emit these events from inside the library code.

**NOTE:** I extended the ws client in my fork enough to be able to test this functionality.

### Example Usage for a User (Event Listening)
```cpp
#include <disccord/ws/client.hpp>

using namespace disccord;
using namespace disccord::ws;

int main()
{
    // stuff to get token etc
    // ...

    discord_ws_client client {token, token_type};

    // events can be listened to and acted on as such
    client.event(event::READY, [&client](){
        // do stuff now that client is ready
    });
    
    client.event(event::MESSAGE_CREATE, [&client](models::message msg){
        // do stuff with message
    });
    
    // <more events here>
    
    // then connect etc
    client.connect().wait();
}
```

### Example Usage in the Library (Event Dispatching)
```cpp
// inside ws/client.cpp


// in some function that is handling the opcode::DISPATCH case, may have something like this:
case event::MESSAGE_CREATE:
{
    // get message data from the frame
    auto msg = frame->get_data<disccord::models::message>();
    
    // emit message obj
    // will execute the users func/lambda if they have a client.event() listener for this event
    dispatcher.emit(event::MESSAGE_CREATE, msg);
    
    // do some extra processing for cache etc
    break;
}
```

### CODE REVIEW

**Comment by abuneri** [comment]
@FiniteReality thoughts?

**Comment by FiniteReality** [comment]
My thoughts right now are that you're jumping too far ahead at the moment; I haven't done any handling of the WS frames, and you're trying to find ways of handling events.

I'm going to put this on hold while I figure out the best approach for this.

**Comment by FiniteReality** [comment]
Errr, what happened here, git? 😛

**Comment by FiniteReality** [comment]
I'm going to close this so you can re-open it so we can have a, er, more linear pull request.

Because whatever the *hell* happened here is confusing me.

**Comment by abuneri** [comment]
LOL, will do xD

**Pull request closed without merging**
